// Code generated by reset generator; DO NOT EDIT.

package resetexample

// Reset resets the ResetableStruct fields to their zero values
func (x *ResetableStruct) Reset() {
	if x == nil {
		return
	}
	x.i = 0
	x.str = ""
	x.b = false
	if x.strP != nil {
		*x.strP = ""
	}
	if x.s != nil {
		x.s = x.s[:0]
	}
	if x.m != nil {
		clear(x.m)
	}
	if x.child != nil {
		*x.child = ResetableStruct{}
	}
	if x.slice != nil {
		x.slice = x.slice[:0]
	}
	if x.mapped != nil {
		clear(x.mapped)
	}
}

// Reset resets the NestedStruct fields to their zero values
func (x *NestedStruct) Reset() {
	if x == nil {
		return
	}
	x.name = ""
	x.age = 0
}

// Reset resets the ComplexStruct fields to their zero values
func (x *ComplexStruct) Reset() {
	if x == nil {
		return
	}
	x.primitive = 0
	x.stringVal = ""
	x.boolVal = false
	x.floatVal = 0
	if x.ptrInt != nil {
		*x.ptrInt = 0
	}
	if x.ptrString != nil {
		*x.ptrString = ""
	}
	if x.sliceInt != nil {
		x.sliceInt = x.sliceInt[:0]
	}
	if x.sliceString != nil {
		x.sliceString = x.sliceString[:0]
	}
	if x.mapIntString != nil {
		clear(x.mapIntString)
	}
	if x.mapStringInt != nil {
		clear(x.mapStringInt)
	}
	if x.nested != nil {
		*x.nested = NestedStruct{}
	}
	if x.sliceNested != nil {
		x.sliceNested = x.sliceNested[:0]
	}
	if x.sliceOfStructs != nil {
		x.sliceOfStructs = x.sliceOfStructs[:0]
	}
}
